// INCOLLA QUI I DATI DEL TUO PROGETTO SUPABASE
// Li trovi in Supabase: Project Settings > API

const SUPABASE_URL = "INCOLLA_QUI_SUPABASE_URL";
const SUPABASE_ANON_KEY = "INCOLLA_QUI_SUPABASE_ANON_KEY";
